# Generated by Django 6.0.3 on 2026-03-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('metric', models.CharField(default='val_loss', max_length=50)),
                ('metric_direction', models.CharField(choices=[('min', 'Lower is better'), ('max', 'Higher is better')], default='min', max_length=3)),
                ('time_budget', models.IntegerField(default=60, help_text='Training time budget in seconds')),
                ('prepare_cmd', models.CharField(default='uv run python prepare.py', max_length=500)),
                ('train_cmd', models.CharField(default='uv run python train.py', max_length=500)),
                ('editable_files', models.JSONField(default=list, help_text='e.g. ["train.py"]')),
                ('readonly_files', models.JSONField(default=list, help_text='e.g. ["prepare.py"]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
